### ISSUE TITLE
New Applet: Philips Hue

### ISSUE THREAD

**Issue by DisabledMonkey** [DasKeyboard/q-marketplace#10]
Here is an applet I built to display whether or not hue lights are turned on/off.
https://github.com/DisabledMonkey/daskeyboard-applet--hue

It is 99% done but I did have a few questions/feature requests before releasing it.

1.
One thing I would like this applet to do is to be able to turn the lights on or off as well.
I found a library to get keypress events (https://github.com/wilix-team/iohook), that way i can look for ctrl-shift-{applet-key} and toggle the lights when this is pressed.
This library works great when debugging using
`node index.js dev '{ <config> }'`
but when i attempt to load the applet within the daskeyboard software, just trying to require that iohook library causes the applet to crash.
Is there a place i can look for a log to see what exact error i am running into, or do you have any other ideas on how I can debug and/or fix this problem?

2.
My second thought was to instead include a button to toggle the lights within one of the dialogs that are shown when using the q key.
![image](https://user-images.githubusercontent.com/52090243/60393021-a0a28980-9adc-11e9-9012-688eae2c9338.png)
![image](https://user-images.githubusercontent.com/52090243/60393025-b3b55980-9adc-11e9-909c-8d077c07bfd2.png)
It appears there currently wouldn't be a way to accomplish this, but might be a nice feature to allow triggering of code within the applet with some sort of button/link click from those dialogs. 

3.
My last question/request is in regards to the config questions.
https://www.daskeyboard.io/applet-development/user-questions/
I am allowing users to select which rooms lights they want to monitor.  
![image](https://user-images.githubusercontent.com/52090243/60401426-4d1d5380-9b4f-11e9-9038-fb8ea6cded27.png)
The first time loading the applet, they must first authenticate the app with their hue bridge, meaning it can't get a list of rooms until this is done.  For now, i have it displaying a message in the drop down telling them to hit the button on their hue bridge.  The problem is, after they have done this, there is no way to refresh the list without cancelling out and re-adding the applet.  The documentation states: 'Note: With the dynamic dropdown, the call to the options method will be made only once to get all the options at the same time.'.  It would be a nice feature to allow a refresh button to be placed next to the dropdown to trigger the list to repopulate (at least for my applet).

So, as it is, the app is semi workable, the initial setup just isn't quite straight forward and it doesn't have the added functionality of being able to turn the lights on and off.

Sorry for the wall of text.

**Comment by fabiendv** [comment]
1. For security reasons, we do not allow to get the key press event.
2. Right now, the only way to do it, it's going through IFTTT. However the setup is difficult. We are working on an easier way to do it with a new Q software version.
3. Nice suggestion. We will work on it. However, this development needs a new Q software version too.

For my part, this version seems to work and seems to be ready to release. I will just check it with a Philips HUE light (how to configure the bridge, etc.) 
For your suggestions, you can keep it in mind for a second version of your applet.

Thanks,

**Comment by DisabledMonkey** [comment]
1. Understandable. Perhaps a compromise would be giving the applet a way to register an event listener that would get triggered when one of the applets keys is pressed with modifiers (ie. ctrl-shift), that would only give the key's relative x,y value from where it was placed on the keyboard. Such as an applet placed spanning the b,n,m keys would give give 1,3 (0,2 if zero indexed) when m is pressed (ie. wouldn't know which specific character was pressed but would know which applet key was pressed). 

1b. I was actually thinking of doing a words per minute / keys per second applet next, but without ability to listen to key presses this wouldn't be possible.  Perhaps getting some statistics like that could be added to the q rest api? Something like /api/2.0/status that could return a bunch of interesting stuff (uptime, firmware version, avg keys per second, avg words per minute, light brightness, etc)

2. Thanks, will have to do some research, although if there is possibly an easier way of doing something similar to that coming down the road, I probably will just wait and see for that.

3. With how this functions currently, I could see the user getting confused at what to do the first time adding the applet.  As they have to load the applet, hit the button on their hue bridge, then hit cancel on the applet and then re-add the applet before seeing the list of rooms.  Perhaps the text we put on that configure page could guide them through that, but a refresh button would make that particular flow a bit easier. It may be worth delaying releasing this applet until there is a better way of handling that within the q software, but i'll leave that up to you.

Thanks for the response and help.

**Comment by fabiendv** [comment]
1. I will talk with the team to decide how can we implement this feature.
1b. We will figure it out the best way how can we make it. There is another [applet](https://github.com/brandonschabell/daskeyboard-applet-sentiment-analysis/issues/1) that needs this feature.
2. We will let you know.
3. For now, I updated the sentence in the drop-down. It's pretty clear.

The review is done. I have one question before making the pull request and releasing, what is the name of your applet?
- Hue
- Philips Hue 

For my part, "Philips Hue" seems to be more appropriate. In this case, we need to update few things (repository's name, applet's name, etc.) Let me know, I will do the update.

**Comment by DisabledMonkey** [comment]
I agree, Philips Hue would probably be better as it is more specific.
Thanks

**Comment by fabiendv** [comment]
You should have received a pull request.
Thank you for this contribution and your suggestions!

**Comment by DisabledMonkey** [comment]
Renamed repo daskeyboard-applet--philips-hue
Merged and tagged v1.0.0
Thanks
