### ISSUE TITLE
Q Applet: Server Ping

### ISSUE THREAD

**Issue by chbakouras** [DasKeyboard/q-marketplace#14]
A new release is available for Q Applet: Server Ping.
https://github.com/chbakouras/daskeyboard-applet--server-ping/releases/tag/v1.1.0

This release introduces the features bellow:

* Display server URL in the Q dashboard.  Useful if you need to ping multiple servers
* Allow modification of ping interval
* Allow specification of desired HTTP response code

https://github.com/chbakouras/daskeyboard-applet--server-ping

Thanks!

**Comment by Mubramaj** [comment]
Hi @chbakouras ,

I am sorry for the delay. Your applet has been updated on the Marketplace.

Thanks again for your contribution
