### ISSUE TITLE
New Applet: Jenkins Pipeline

### ISSUE THREAD

**Issue by chrsmrtn-** [DasKeyboard/q-marketplace#15]
Have a new applet for the store! This one will monitor a pipeline and report it's status to the keyboard.

https://github.com/chrsmrtn-/daskeyboard-applet--jenkins

**Comment by chrsmrtn-** [comment]
Hello, just wanted to ping this one :) Anyone watching for new applets?

**Comment by eisenwr** [comment]
I think Das Keyboard has/is abandoning the applets. And this was a really great idea too.

**Comment by chrsmrtn-** [comment]
Hello again. Pinging with a new applet 😎

**Comment by Mubramaj** [comment]
HI @chrsmrtn- ,

I am sorry for the late reply. 

I took a look at the Applet. We require some little changes but then I will be more than happy to deploy your applet to the Q Applet marketplace.

- We require the icon to be 512x512px
- Can you please add comments to the index.js
- just to make sure can you confirm that the command to run the tests is 'yarn test'

**Comment by chrsmrtn-** [comment]
Hi @Mubramaj 

Thank you soo much for getting back to me. I'll get on the feedback and update here when it's ready

Chris

**Comment by chrsmrtn-** [comment]
Okay @Mubramaj comments addressed. I confirmed that tests can be run via `yarn test`

**Comment by chrsmrtn-** [comment]
Hey @Mubramaj, sticking while the iron is still hot 😁 Anh news on this? We all set?

**Comment by Mubramaj** [comment]
Hi @chrsmrtn- ,

Thank you for making those updates.

I started testing it on my local machine and I opened some issues on your repo

**Comment by chrsmrtn-** [comment]
Thanks @Mubramaj 

I addressed the function reference issue so things should work now once you pull from master.  I answered your question in the issue regarding "api key" format

**Comment by chrsmrtn-** [comment]
@Mubramaj hey just wanted to ping ya about this :)

**Comment by chrsmrtn-** [comment]
*puts hand over iron* Yep, still hot :) Hey @Mubramaj any news on this?

**Comment by Mubramaj** [comment]
Hi @chrsmrtn- 
I am sorry for the late reply. I will look at this ASAP.

**Comment by Mubramaj** [comment]
Hi @chrsmrtn- 

Your Applet is up and running. Thank you for contribution and your patience.
