### ISSUE TITLE
Weather-international applet not connecting

### ISSUE THREAD

**Issue by teunmooij** [DasKeyboard/q-marketplace#18]
I've installed the Weather-International applet. It keeps blinking and is not picking up the forecast. 

Before I registered this issue I made sure that:
- I'm not experiencing any internet issues
- Other applets that use internet connection work just fine
- This applet is owned by Das Keyboard

There's a ticket about it in the repo of this applet, but nobody is replying to the issue

**Comment by fabiendv** [comment]
It will be fix into the release coming up.

Thank you
