### ISSUE TITLE
Philips Hue applet updated

### ISSUE THREAD

**Issue by DisabledMonkey** [DasKeyboard/q-marketplace#22]
The [Philips Hue Applet](https://github.com/daskeyboard/daskeyboard-applet--philips-hue) has been updated to work with Das Keyboard Q version 4 (which broke it).
Also switched to using Philips Hue v2 api and using their Server Side Events to detect light changes versus polling for them every 5 seconds. (so much more performant)

Release [v1.0.1](https://github.com/DisabledMonkey/daskeyboard-applet--philips-hue/releases/tag/v1.0.1)

**Comment by Mubramaj** [comment]
Nice improvements thank you
