### ISSUE TITLE
Applet Contribution: CircleCI

### ISSUE THREAD

**Issue by brandonschabell** [DasKeyboard/q-marketplace#4]
I created a new applet for CircleCI integration and would love to get it on the marketplace. Here's the repo: [https://github.com/brandonschabell/daskeyboard-applet-circleci](https://github.com/brandonschabell/daskeyboard-applet-circleci)

**Comment by supercobra** [comment]
Great contribution!

**Comment by brandonschabell** [comment]
Thank you! Let me know if there's anything else I can do. 

P.S. I just got a 5Q keyboard - it's hands down the nicest keyboard I've ever used. Keep it up!

**Comment by fabiendv** [comment]
I have published it in the Das Keyboard Q marketplace. Thank you for your contribution.
