### ISSUE TITLE
New Applet: GPU Usage

### ISSUE THREAD

**Issue by brandonschabell** [DasKeyboard/q-marketplace#5]
Hey, I created a new applet. This one tracks GPU memory usage. I do a lot of deep learning, so this is helpful to monitor resource utilization. I'm sure gamers would find it helpful too. Hope you like it!

https://github.com/brandonschabell/daskeyboard-applet-gpu-usage

**Comment by fabiendv** [comment]
I have published it in the Das Keyboard Q marketplace. Thank you for your contribution.
