### ISSUE TITLE
New Applet: Mini-Meters

### ISSUE THREAD

**Issue by corykim** [DasKeyboard/q-marketplace#6]
Extensible system meter app, displays one signal per key using consistent color schemes. Currently supports:

- CPU
- Memory
- Average Load
- nVidia GPU

**Comment by corykim** [comment]
https://github.com/corykim/daskeyboard-applet--mini-meters

**Comment by corykim** [comment]
@fabiendv I've detached the fork, so you should be able to now fork it back.

**Comment by fabiendv** [comment]
@corykim thanks, I deployed it.
