### ISSUE TITLE
New Applet: Crypto Watch

### ISSUE THREAD

**Issue by Wolfe1** [DasKeyboard/q-marketplace#8]
https://github.com/Wolfe1/daskeyboard-applet--crypto-watch

**Comment by fabiendv** [comment]
We are on it.

**Comment by fabiendv** [comment]
You should have received a pull request with recommendations.

**Comment by fabiendv** [comment]
I will deploy your version 1.0.0. Can you create a tag v1.0.0 into your branch?

You can do the recommendations whenever you want with a new version.

Thanks,

**Comment by Wolfe1** [comment]
Done.
