### ISSUE TITLE
New Applet: Clock

### ISSUE THREAD

**Issue by DisabledMonkey** [DasKeyboard/q-marketplace#9]
Missed having a clock on my keyboard like on my last keyboard, so i built one.
https://github.com/DisabledMonkey/daskeyboard-applet--clock
Hopefully it is useful, although it basically takes up top two rows the keyboard just to display the time :)

Love the 5q keyboard by the way!

**Comment by fabiendv** [comment]
We are on it. If it's useful for you, it will be for others.

We are glad you like it!

**Comment by fabiendv** [comment]
You should have received a pull request.

**Comment by DisabledMonkey** [comment]
@fabiendv Merged and tagged v1.0.0
Thanks
